
import { Inter } from "next/font/google";
import "./globals.css";
import { getSession } from "./auth";
import Providers from "./providers";
const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default async function RootLayout({ children }) {

  const session = await getSession()
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers session={session}>


          {children}

        </Providers>
      </body>
    </html>
  );
}
